### ISSUE TITLE
We can do a little better with the sendmail_users mail alias handling

### ISSUE THREAD

**Issue by jsnshrmn** [OULibraries/ansible-role-sendmail#1]
currently

```
sendmail_users:
  - apache
  - root
```

just maps the listed local user accounts to the authenticated account.  Next release should have something like:

```
sendmail_aliases:
  - user: apache
    email_address: foo@example.com
    email_display: Foo Team at Example
  - root
    email_address: bar@example.com
    email_display: Bar Team at Example
```

Where email_display is modifying the 5th column of the /etc/passwd entry for the listed user.
This will make sure that even if an application isn't appropriately setting the display name for the sender, we'll get curated headers.
